"""add docker debug container ids

Revision ID: d40e59390ffd
Revises: d57297145566
Create Date: 2024-04-07 00:03:42.340777

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d40e59390ffd"
down_revision: Union[str, None] = "d57297145566"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coderun", sa.Column("pyro_docker_debug_id", sa.LargeBinary(length=12), nullable=False)
    )
    op.add_column(
        "coderun", sa.Column("interpret_docker_debug_id", sa.LargeBinary(length=12), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coderun", "interpret_docker_debug_id")
    op.drop_column("coderun", "pyro_docker_debug_id")
    # ### end Alembic commands ###
