"""create all nessesary tables

Revision ID: d57297145566
Revises:
Create Date: 2024-04-06 18:07:19.886218

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d57297145566"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("session_key", sa.String(length=48), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "coderun",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("pyro_docker_id", sa.LargeBinary(length=12), nullable=False),
        sa.Column("pyro_docker_status", sa.Enum(native_enum=False), nullable=False),
        sa.Column("interpret_docker_id", sa.LargeBinary(length=12), nullable=False),
        sa.Column("interpret_docker_status", sa.Enum(native_enum=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "builderror",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["coderun.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "runmissmatcherror",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.Column("interpret_run_result", sa.String(), nullable=False),
        sa.Column("pyro_mapped_result", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["coderun.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "runresult",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.Column("pyro_compilation_time", sa.Interval(), nullable=False),
        sa.Column("pyro_runtime", sa.Interval(), nullable=False),
        sa.Column("pyro_memory_usage", sa.Integer(), nullable=True),
        sa.Column("interpret_compilation_time", sa.Interval(), nullable=False),
        sa.Column("interpret_runtime", sa.Interval(), nullable=False),
        sa.Column("interpret_memory_usage", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["coderun.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("runresult")
    op.drop_table("runmissmatcherror")
    op.drop_table("builderror")
    op.drop_table("coderun")
    op.drop_table("session")
    # ### end Alembic commands ###
